### ISSUE TITLE
Handling open project

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_breadcrumbs#1]
@Alexey-T 

When project is opened, should folders above project-root be of a different color? Or just hide them?

For choosing project-root I probably will give an option like in LSP-plugin:
* root_dir_source - LSP server root directory source (accepts list of values for fallback):
    * 0 - parent directory of '.cuda-proj'
    * 1 - first directory in project
    * 2 - project main-file's directory

**Comment by Alexey-T** [comment]
Folders color - maybe add an option (bool or 3 state int).

**Comment by Alexey-T** [comment]
Root dir source - ok

**Comment by halfbrained** [comment]
Added both

> Folders color - maybe add an option (bool or 3 state int).

`show_root_parents` - bool, either hide parents, or show with different color.
