### ISSUE TITLE
suggestion for unix only

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#10]
on unix: let's make the option: "show ~ as the first cell".
ie instead of

/ | home | user | dirs

show

~ | dirs

**Comment by Alexey-T** [comment]
it will make nicer look here-
![Screenshot from 2021-07-05 10-51-39](https://user-images.githubusercontent.com/4154978/124436793-06d2de80-dd7f-11eb-8381-99a2736157cd.png)

**Comment by halfbrained** [comment]
Added
