### ISSUE TITLE
33ms startup even for untitled doc on start

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#12]
![Screenshot from 2021-07-05 15-39-42](https://user-images.githubusercontent.com/4154978/124472855-49a8ac80-dda7-11eb-88b7-ddc6d3520583.png)

**Comment by halfbrained** [comment]
Hm... it is 1-3ms for me. Probably project manager again? :)

Try replacing `get_project_dir()` in `breadcrumbs.py` with this, then restart a few times:
``` python
def get_project_dir():
    return None
```

**Comment by Alexey-T** [comment]
now its 14 ms!

**Comment by halfbrained** [comment]
I can't really improve startup time further than it is now... I can delay the statusbar appearance and work a bit, it will probably improve startup, but I'm not sure it will be better?

**Comment by Alexey-T** [comment]
let's test 'is ProjMan already loaded.
```
Test for the module name in the sys.modules dictionary:

import sys

modulename = 'datetime'
if modulename not in sys.modules:
    print 'You have not imported the {} module'.format(modulename)

```

**Comment by halfbrained** [comment]
Yes, `cuda_project_man` for me is in the sys.modules before I import it.

**Comment by Alexey-T** [comment]
and not for me. I turned off ProjMan's option "Load on app start"

**Comment by Alexey-T** [comment]
so Cud start will be faster if you add this check for sys.modules

**Comment by halfbrained** [comment]
Oh, I see, that's clever :) will add the check

**Comment by halfbrained** [comment]
Added, got me from 9 to 6ms. Yay :)
