### ISSUE TITLE
left/bottom of popup form is not nice

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#15]
now: x=cell_right, y=cell_bottom
I suggest: x=cell_left, y=cell_top

**Comment by Alexey-T** [comment]
also it's good to limit popup's height by Cud window height minus delta.
https://wiki.freepascal.org/CudaText_API#app_proc_-_Screen_coordinates

**Comment by Alexey-T** [comment]
текущая позиция окей только для случая когда форма не влезает по высоте и ее надо сдвинуть пониже (когда Куд на самом верху монитора).
т.е. текущую позицию можно в этом случае юзать.
а когда все влезает - сделать так чтобы форма как бы висела НАД контролом.

**Comment by halfbrained** [comment]
Изменил:
![bread_pos](https://user-images.githubusercontent.com/74829192/124502481-42e06080-ddcc-11eb-8315-e004ae60939b.png)

(надеюсь правильно понял :) )
