### ISSUE TITLE
Is filtering/search needed?

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_breadcrumbs#2]
I think it would be nice to highlight matching files as you type in the tree-dialog, but `treeview` does not provide api for that.

**Comment by halfbrained** [comment]
@Alexey-T

**Comment by Alexey-T** [comment]
But how does it relate to breadcrumb?

**Comment by halfbrained** [comment]
![ss](https://raw.githubusercontent.com/halfbrained/cuda_breadcrumbs/main/readme/screenshot.png)

In the tree dialog, quick search in large folders

**Comment by Alexey-T** [comment]
dlg_proc allows to set 'key_preview':True so your form can geet pressed keys in memory, and perform some jumps. right?

**Comment by halfbrained** [comment]
I didn't want removing non-matching files from tree. Jumping to matches is better, also will add keys to jump to next/previous matches.

**Comment by Alexey-T** [comment]
Ok,agree. I stil don't get idea how this jump will work

**Comment by Alexey-T** [comment]
(form gets pressed keys via on_key_down event)

**Comment by halfbrained** [comment]
Just added, I would appreciate some feedback on how intuitive this is :)

Typing anywhere in the dialog modifies search string, `F3`/`Shift+F3` to search forward/back
