### ISSUE TITLE
issue with 2 files in a single tab

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#22]
start Cud w/o files.
call 'settings- default/user'. we have 2 bars
![Screenshot from 2021-07-06 18-33-33](https://user-images.githubusercontent.com/4154978/124628221-eee78180-de88-11eb-8bea-8994037a5e39.png)

quit Cud with "ui_reopen_session":true.
start again.

2 files are here but we have 1 bar.
![Screenshot from 2021-07-06 18-33-28](https://user-images.githubusercontent.com/4154978/124628153-e000cf00-de88-11eb-865c-86f3a9e2acea.png)

**Comment by halfbrained** [comment]
Yes, second bar appears when the other side gets focused. And I see some other weird stuff with this configuration. Investigating :)

**Comment by halfbrained** [comment]
Should work now (fingers crossed)

**Comment by Alexey-T** [comment]
not ok yet, I started Cud w/o files, called 'settings- default/user' and in 2/3 cases I got
only 1 bar
![Screenshot from 2021-07-07 17-10-55](https://user-images.githubusercontent.com/4154978/124774316-629b9400-df46-11eb-89c9-f6116e1d1615.png)

**Comment by halfbrained** [comment]
Should work now (fingers crossed)

**Comment by Alexey-T** [comment]
Good!
