### ISSUE TITLE
maybe highlight the button which is pressed until Popup hides?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#24]
is it easy to do? not highly needed. nice to have.

**Comment by Alexey-T** [comment]
solved.

**Comment by halfbrained** [comment]
Please elaborate. On the current beta for me it is not. I wanted to try, was just prioritizing bugs first :)

**Comment by Alexey-T** [comment]
ops, you 're right

**Comment by halfbrained** [comment]
Added. Looks nice I think

![highlight_0](https://user-images.githubusercontent.com/74829192/124926772-95a55c80-e006-11eb-8409-a1f215ced461.png)

![hili2](https://user-images.githubusercontent.com/74829192/124926774-963df300-e006-11eb-8b74-286e6921148a.png)
