### ISSUE TITLE
Click in last part of path shows/disappear the dialog.

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_breadcrumbs#26]
I think the click in last part don't need be allowed, currently shows so quickly the dialog and immediately hides it.

![CUsersJairo Mart_2021-07-06_13-34-20](https://user-images.githubusercontent.com/5806694/124650263-25a8a200-de5f-11eb-8f1b-91a022355ac1.png)

**Comment by Alexey-T** [comment]
seems only Win10 problem. what API fails here?

**Comment by JairoMartinezA** [comment]
![LastClick](https://user-images.githubusercontent.com/5806694/124655549-98b51700-de65-11eb-925e-855be8f99a0a.gif)

**Comment by Alexey-T** [comment]
I see, and I trust you anyway

**Comment by halfbrained** [comment]
It's a problem with windows paths, fixing it. (Until now only tested it on linux :) )
