### ISSUE TITLE
Win has C:\Users\UserName folder - it's good to replace 3 buttons with e.g. [user]

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#28]
https://user-images.githubusercontent.com/5806694/124655549-98b51700-de65-11eb-925e-855be8f99a0a.gif

**Comment by Alexey-T** [comment]
OTOH, it is very minor suggestion, u may ignore.

**Comment by halfbrained** [comment]
Hm, I never used my user directory on windows, so I didn't include it in `tilde_home` option. If it also can be useful on windows... should I rename the `tilde_home`?

**Comment by Alexey-T** [comment]
cannot find what is the Win home dir. 
https://stackoverflow.com/questions/9228950/what-is-the-alternative-for-users-home-directory-on-windows-command-prompt - this is a __mess__

**Comment by halfbrained** [comment]
`os.path.expanduser` handles changed home directory, if that is your concert
![winhome0](https://user-images.githubusercontent.com/74829192/124864873-56551c80-dfc2-11eb-8f25-a71d256615ea.png)
![winhome2](https://user-images.githubusercontent.com/74829192/124864880-59500d00-dfc2-11eb-9c1c-1daa5549d1af.png)

**Comment by Alexey-T** [comment]
Ok then, ~ is c:\users\name.

**Comment by halfbrained** [comment]
Changed. Now `tilde_home` used on all OS's. Checked on Win7 and macos

**Comment by Alexey-T** [comment]
great!
