### ISSUE TITLE
hide/unhide, or toggle this addon at gui

### ISSUE THREAD

**Issue by MiroslavMatas** [halfbrained/cuda_breadcrumbs#29]
it can be usefull for me - if I will be able to hide/toggle it… 
want to see it only if necessary… not always (without usage - just decrease working area)
so - if will be possible to add command "toggle breadscrum", that will be good…

works fine, looks to me…

**Comment by halfbrained** [comment]
Almost done, but the day is at an end :)

Also will add a command to just show tree in the current document's directory, should be useful

**Comment by halfbrained** [comment]
Added (2fcba6916ff23dd7752ada371059567e75a33930, 652aeac38616abb10511bab732473383805d3beb)
