### ISSUE TITLE
Fallback for code navigation, when LSP plugin is missing

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_breadcrumbs#3]
@Alexey-T Before I add LSP support, maybe add an option for using ranges from Code-Tree ranges? It probably will perfectly well in most use-cases.

(Especially since LSP servers usually do not provide a *tree* of document symbols, so I can't properly get a proper breadcrumbs-path)

**Comment by Alexey-T** [comment]
maybe make such an option:

0: disable symbols-path (show only file system path)
1: add symbols-path from LSP
2: add symbols path from code-tree if possible

what do u think.

**Comment by halfbrained** [comment]
Yes, probably will go with that.

**Comment by halfbrained** [comment]
It appears that data from Code-tree is sufficient, no need for LSP to get involved
