### ISSUE TITLE
little glitch with shorting by '...'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#32]
settings_default ->
![Screenshot from 2021-07-07 18-19-53](https://user-images.githubusercontent.com/4154978/124786002-063d7200-df50-11eb-9209-981f202e1abf.png)

**Comment by halfbrained** [comment]
Am I being too literal here? :) What am I supposed to do when there is only one character to remove?

**Comment by Alexey-T** [comment]
if only 1 char to remove - don't remove. if at least 2 chars to remove- do

**Comment by halfbrained** [comment]
changed
