### ISSUE TITLE
change separator char to os.sep, maybe?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#34]

**Comment by halfbrained** [comment]
Maybe an option? For example for me os.sep is a bit too low contrast, event white.

(And I think pink hearts look very cute :D )
![hurtz](https://user-images.githubusercontent.com/74829192/124800316-2d9b3b80-df5e-11eb-80cd-307449077234.png)

**Comment by Alexey-T** [comment]
yes, an option.

**Comment by halfbrained** [comment]
Added (d682540859a6acca3d5bd35b3acbe0ea8f356741)
