### ISSUE TITLE
Clicking on popup on taskbar stops of open the popup

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_breadcrumbs#35]
![out](https://user-images.githubusercontent.com/25956396/124806706-607c0a00-df33-11eb-831c-b1e72491d5fb.gif)

**Comment by Alexey-T** [comment]
@halfbrained 2 related options:
![Screenshot from 2021-07-07 20-59-09](https://user-images.githubusercontent.com/4154978/124807220-355ede00-df66-11eb-8d34-665ad9f82f34.png)

**Comment by eltonfabricio10** [comment]
Fixed with: `"ui_dialogs_in_taskbar__linux": false` in user config

**Comment by halfbrained** [comment]
I'm not sure where the issue originates for now, but at some point plugin begins to receive three 'on_deact' events imemdiately after tree-dialog is shown...

![deacts](https://user-images.githubusercontent.com/74829192/124877875-329ad200-dfd4-11eb-9f67-5b4415479ccb.png)


Since it appears not to be my fault - I will come back to it a bit later.

**Comment by Alexey-T** [comment]
I made small plugin to show on_app_activate/deactivate. it doesnt show 3 calls, nor 1 call. it may be a lazarus bug... need repro

**Comment by halfbrained** [comment]
@Alexey-T Attaching repro plugin. 

Steps:
1. run the plugin's command `_Repro\dlg on_deacts` - will show a dialog
2. switch to a window of a different program
3. click on dialog's button on taskbar to minimize the dialog
4. repeat item '1' -- this time dialog will not appear, you will see several 'on_deact' messages from plugin in Console.

A desktop-environment-independent alternative to items 2 and 3:
``` shell
# find dialog's id
name:~$ xdotool search --name deact_repro
100666297

# minimize dialog window
name:~$ xdotool windowminimize 100666297
```

[cuda__repro_dlg.zip](https://github.com/halfbrained/cuda_breadcrumbs/files/6785395/cuda__repro_dlg.zip)

**Comment by Alexey-T** [comment]
maybe Breadcrumb must not react to on_app_deact at all? it can show the popup longer, its ok.

**Comment by halfbrained** [comment]
I have `on_deact` on the tree-dialog, to hide it when you click outside, not `on_app_deactivate`.

If there is a better way to achieve this - I'm open to suggestions :)

**Comment by halfbrained** [comment]
Should be fixed

**Comment by eltonfabricio10** [comment]
> Should be fixed

This bug still continues

**Comment by eltonfabricio10** [comment]
> Should be fixed

This bug still continues

**Comment by halfbrained** [comment]
Hm... weird.

Could you change the line 24 in `cuda_breadcrumbs/dlg.py` and check again? -- from:
``` python
IGNORE_INPUT_PERIOD = 0.05 # sec
```
to
``` python
IGNORE_INPUT_PERIOD = 1 # sec
```

**Comment by eltonfabricio10** [comment]
> Hm... weird.
> 
> Could you change the line 24 in `cuda_breadcrumbs/dlg.py` and check again? -- from:
> 
> ```python
> IGNORE_INPUT_PERIOD = 0.05 # sec
> ```
> 
> to
> 
> ```python
> IGNORE_INPUT_PERIOD = 1 # sec
> ```

This crashes the system when clicking on cell

**Comment by Alexey-T** [comment]
crashes the OS Ubuntu? weird. :(

**Comment by eltonfabricio10** [comment]
> IGNORE_INPUT_PERIOD = 1 # sec

Yep, with this change

**Comment by Alexey-T** [comment]
@halfbrained Pls reopen.

**Comment by halfbrained** [comment]
> This crashes the system when clicking on cell

Wow... can you tell me your OS and desktop-environment? I'll try to investigate

**Comment by eltonfabricio10** [comment]
> > This crashes the system when clicking on cell
> 
> Wow... can you tell me your OS and desktop-environment? I'll try to investigate

OS: Ubuntu 20.04
DE: LXDE
WM: Openbox

**Comment by halfbrained** [comment]
For me it does not crash the system, but just hangs `openbox` for a few minutes (or I can kill the process manually from `Ctrl+Alt+F3`). 
![hanged](https://user-images.githubusercontent.com/74829192/125162601-771f9c80-e191-11eb-8db3-3c4cf1740703.png)

Then I think cudatext crashes with SIGSEGV (signal 11)? this is `apport.log`
```
ERROR: apport (pid 2248) Sat Jul 10 13:51:23 2021: called for pid 2238, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 2248) Sat Jul 10 13:51:23 2021: executable: ~/Downloads/cu/cudatext (command line "./cudatext")
ERROR: apport (pid 2248) Sat Jul 10 13:51:23 2021: executable does not belong to a package, ignoring
```

Log from plugin doesn't show anything suspicious (except multiple consecutive `on_deact`)
```
14:57:42.131500### SHOW DIR: ('~/Downloads/cu/py/cuda_breadcrumbs/dlg.py', '~/Downloads/cu/py/cuda_breadcrumbs')
14:57:42.165226.tree click
14:57:45.014936.on_deact
14:57:45.016043.hide
14:57:45.017205.on_hide

14:57:48.328204### SHOW DIR: ('~/Downloads/cu/py/cuda_breadcrumbs', '~/Downloads/cu/py')
14:57:48.363254.tree click
14:57:48.371559.on_deact
14:57:49.673272.on_deact
14:57:49.673707.hide
14:57:49.674664.on_hide

14:57:49.766662### SHOW DIR: ('~/Downloads/cu', '~/Downloads')
14:57:49.770579.tree click
14:57:50.606848.on_deact
```

Sorry, I have no idea how to fix this.
@Alexey-T Thoughts?

**Comment by Alexey-T** [comment]
I made a workaround for multi on _deact. beta. does it help.

**Comment by halfbrained** [comment]
No change

**Comment by halfbrained** [comment]
@eltonfabricio10 Crash and the initial issue should be fixed

**Comment by eltonfabricio10** [comment]
I will test

**Comment by eltonfabricio10** [comment]
> @eltonfabricio10 Crash and the initial issue should be fixed

Congratulations my friend! 👍
