### ISSUE TITLE
new screenshot

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#36]
![scr](https://user-images.githubusercontent.com/4154978/124809138-722bd480-df68-11eb-98a9-48cc523f1a20.png)

**Comment by eltonfabricio10** [comment]
I liked it.... "/" instead ">"

**Comment by Alexey-T** [comment]
Elton, I already asked this (see issues list)

**Comment by eltonfabricio10** [comment]
> Elton, I already asked this (see issues list)

is true hahaha

**Comment by halfbrained** [comment]
Thanks, updated
