### ISSUE TITLE
separator char - how Unix/Win handle the same option

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#38]
first saving of config - you write to config '/' char (linux).
now Win app reads that config and it cannot set Win separator!
suggestion - consider empty value of option as os.sep.

**Comment by eltonfabricio10** [comment]
Initial setting (Win7)

![Screenshot_1](https://user-images.githubusercontent.com/25956396/124992105-f047b400-e018-11eb-943e-ef191c2643c0.png)

**Comment by eltonfabricio10** [comment]
> first saving of config - you write to config '/' char (linux).
> now Win app reads that config and it cannot set Win separator!
> suggestion - consider empty value of option as os.sep.

I agree, consider empty value

![Screenshot_2](https://user-images.githubusercontent.com/25956396/124992623-998eaa00-e019-11eb-8b31-734a9098b296.png)

**Comment by halfbrained** [comment]
Changed (9fb45519a65525876f1f1b9305121dab225c5513)

I wanted empty string for default cells style, but I'm fine with abandoning that
