### ISSUE TITLE
ERROR: Exception in CudaText for cuda_breadcrumbs.show_tree

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_breadcrumbs#40]
If you click on `Plugins/Breadcrumbs/Show file-tree` in an empty document... It shows this error:

![Captura de tela de 2021-07-10 11-29-47](https://user-images.githubusercontent.com/25956396/125166634-f2258a80-e172-11eb-8213-fcf7313eb8c4.png)

It's good to show a message that you need to open a file first

**Comment by halfbrained** [comment]
Thanks, fixed
