### ISSUE TITLE
colors with theme 'darkwolf'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#41]
Opening Cud with file in session. after a pause I see tree-buttons with black color.
![Screenshot from 2021-07-13 20-51-30](https://user-images.githubusercontent.com/4154978/125501381-869691e5-8a4e-4351-a0ad-044525d7f3b5.png)

**Comment by halfbrained** [comment]
Hm, what do I do with an empty color?

https://github.com/Alexey-T/CudaText/blob/177c7e2941c91514d34a1084a1d647c84b226957/app/data/themes/darkwolf.cuda-theme-ui#L59

**Comment by Alexey-T** [comment]
```
const
  cAppThemeColorsWhichAllowNone: set of TAppThemeColorId =
    [
    apclEdBlockStapleActive,
    apclTabFontActive,
    apclTabCloseBg,
    apclMenuFont..apclMenuSelBg,
    apclStatusFont,
    apclStatusBg
    ];   
```

когда он COLOR_NONE то не применять

**Comment by Alexey-T** [comment]
ie "none" means "don't use this special color".

**Comment by halfbrained** [comment]
Fixed.

On your screenshot - is main statusbar text supposed to be black?

**Comment by Alexey-T** [comment]
when it's 'none' it falls back to 'buttons font'.
