### ISSUE TITLE
'search' cannot go to 'emmet' node in codetree when I type or press F3/shift-F3

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#49]
![Screenshot from 2021-07-19 23-59-32](https://user-images.githubusercontent.com/4154978/126226721-c8894d0f-fc78-4e9f-96f6-6fb90dfbe3ff.png)

cannot go to 3rd node.

**Comment by halfbrained** [comment]
I check for the start of names, `*emme` or `[emme` will work
