### ISSUE TITLE
maybe add "arrow down", "arrow up" buttons to the right on the 'search'?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#50]

**Comment by halfbrained** [comment]
To navigate treeview or filesystem?

**Comment by Alexey-T** [comment]
To find - next, previous, if “search” not empty

**Comment by halfbrained** [comment]
Sure.

You are saying up and down, like SynWrite?

![ud](https://user-images.githubusercontent.com/74829192/126296682-b6553196-ff66-46dc-ac2b-70f925186c8c.png)

Maybe better would be like in CudaText search dialog?

![lr](https://user-images.githubusercontent.com/74829192/126296767-44cadbb7-4e46-4218-aa02-1aff5aa28a15.png)

**Comment by Alexey-T** [comment]
Like in CudaText

**Comment by Alexey-T** [comment]
Cud is better! it will work with any gray theme.

**Comment by halfbrained** [comment]
Added

![search_btns](https://user-images.githubusercontent.com/74829192/126320799-96b5dfe1-b936-4eac-b427-bcad0aeaf32d.png)

**Comment by Alexey-T** [comment]
nice!
