### ISSUE TITLE
consider Cud option for vert-indent on cliking treeview nodes

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#55]
![Screenshot from 2021-07-23 14-14-21](https://user-images.githubusercontent.com/4154978/126774414-13cb5bc9-4420-4d80-be4c-dba5367d0224.png)

you can take abs(N) for N<0. to be simple.

**Comment by Alexey-T** [comment]
cudax_lib gives the API get_opt.

**Comment by halfbrained** [comment]
Done.

Thanks for the tip, I was not aware of this option

**Comment by Alexey-T** [comment]
what is that option is missed in config? you will get 0 and use 0 indent?

**Comment by Alexey-T** [comment]
2) option allows valie 100 !

> for big values N, where abs(N)>=100, make centering vertically

but plugin won't handle 100. Let's revert this - use 5 fixed value.

**Comment by halfbrained** [comment]
> what if that option is missed in config? you will get 0 and use 0 indent?

I think it will fallback on the default value?

ok, reverting
