### ISSUE TITLE
path separator can only be 1 char width

### ISSUE THREAD

**Issue by veksha** [halfbrained/cuda_breadcrumbs#62]
![image](https://user-images.githubusercontent.com/275333/196008936-561fe236-1338-4cbd-aa33-cf74d61b27e6.png)

**Comment by Alexey-T** [comment]
but why do we need len>1 separator?

**Comment by Alexey-T** [comment]
Cud API needs that this separator is one char!

**Comment by veksha** [comment]
which API specifically?
isn't this for render purpose only?

**Comment by veksha** [comment]
> but why do we need len>1 separator?

it's beautiful

**Comment by veksha** [comment]
if it's hard to do, we can close it.

**Comment by Alexey-T** [comment]
hard to do, autosize of cells don't count separ's width, sorry.
