### ISSUE TITLE
Breadcrumbs are not at the bottom and the window will become wider or narrower with successive clicks

### ISSUE THREAD

**Issue by actforjason** [halfbrained/cuda_breadcrumbs#64]
Example
![动画](https://github.com/user-attachments/assets/4336b51a-153b-4aa9-9cd2-18e325ea6ff9)

Config
```ini
[snippet_panel]
folder=Arrows

[python_intel]
environment=C:\Users\Jason\miniconda3\python.exe

[breadcrumbs]
position_bottom=1
root_dir_source=0
show_root_parents=1
file_sort_type=name
tilde_home=1
show_hidden_files=0
max_name_len=100
max_dirs_count=0
path_separator=
code_navigation=2
code_tree_height=0
show_bar=1
dialog_width=400
dialog_height=400

[complete_from_text]
lexers=-,AutoHotkey,markdown,ini files,restructuredtext,properties
min_len=2
case_sens=0
no_comments=1
no_strings=1
what_editors=0
max_lines=100
use_acp=1
case_split=0
underscore_split=1

[color_picker]
recents=#393939,#090909,#303030,#333333,#2b2b2b,#262626,#232323,#252525,#141414,#202020,#ff0000,#d7e4f2,#dfdfdf,#d5d5d5,#d6d6d6,#1f1f1f,#4f270b,#276303,#191919,#68b4ff,#91c8ff,#861515,#ef7676,#e9e9e9,#e3e3e3,#dbd2c4,#dddecf,#e8e7e1,#e4e3dc,#ecebe6
```

**Comment by Alexey-T** [comment]
It is Windows.

- OS has custom scaling?
- Cud has custom value of option "ui_scale"? What if you change it to be like in OS (not value 0)?

**Comment by actforjason** [comment]
Windows system scaling is 125%. After setting cudatext "ui_scale" to 125 and restart, bug still occurs.
![图片](https://github.com/user-attachments/assets/21eb895d-fad4-4c47-8e31-642135c8c6de)

**Comment by Alexey-T** [comment]
bug in CudaText.
this beta is better? for me on linux, bug is fixed.
[cudatext.zip](https://github.com/user-attachments/files/17629789/cudatext.zip)

**Comment by actforjason** [comment]
Yes，it works fine except that the dialog shows at the leftmost edge of window instead of aligning to the click position on the breadcrumbs for .ini or .json files.

![图片](https://github.com/user-attachments/assets/afcd613f-df73-4325-b42e-71ad1e06e942)
![图片](https://github.com/user-attachments/assets/16994a94-f56b-4e0f-804d-151373a0bba6)

**Comment by Alexey-T** [comment]
if was regress in Cud 1.214.7. try the old version 1.213
https://sourceforge.net/projects/cudatext/files/release/1.213.0.2/
it is better with Breadcrumbs?

**Comment by actforjason** [comment]
Version 1.213 works well. My version is 1.219. Is there any way？
![图片](https://github.com/user-attachments/assets/6dd1f964-57a7-4653-be1b-fca235cd5ae7)

**Comment by Alexey-T** [comment]
Investigating..

**Comment by Alexey-T** [comment]
found the bug! fixed.
test this beta
[cudatext.zip](https://github.com/user-attachments/files/17631902/cudatext.zip)
if ok, I will update release to 1.129.0.2.
if ok, close the issue.

**Comment by actforjason** [comment]
Perfect!
