### ISSUE TITLE
VSCode expands tree-items and opens files by _single_ click

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#7]
can we do like it?

**Comment by halfbrained** [comment]
Changed to single click. 

Closing dialog immediately when clicking a file feels a bit weird, but probably ok?

**Comment by Alexey-T** [comment]
Maybe make the option then?

**Comment by halfbrained** [comment]
I would rather not. This is too minor an issue to pollute the option list.

Will add if someone complains - ok compromise? :)

**Comment by Alexey-T** [comment]
ok
