### ISSUE TITLE
when window is too narrow, buttons don't fit- last buttons

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_breadcrumbs#9]
![narr](https://user-images.githubusercontent.com/4154978/124435630-d8a0cf00-dd7d-11eb-8a4d-d940b6af5324.png)

**Comment by halfbrained** [comment]
Do you have some advice on this? :)

I'm not sure what is a good way to handle this, API-wise

**Comment by Alexey-T** [comment]
besides showing '~' item, we cannot fix it.
